<a href="https://colab.research.google.com/github/Roger-Mapoga/CES117V/blob/master/Lab_1_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.0


### Basic operations with TensorFlow

In [2]:
a = 4 + 2j #complex number
b = 6 + 7j

c = a + b
d = tf.square(c)
print(a,b,c,d)



print(a-b)
print(a*b)

(4+2j) (6+7j) (10+9j) tf.Tensor((19+180j), shape=(), dtype=complex128)
(-2-5j)
(10+40j)


### Tensors
As we Know, tensors are array of numbers arranged in space. We can call a vector(1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. Below, find out how to create a [constant](https://www.tensorflow.org/api_docs/python/tf/constant) tensor:

In [3]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print(c)

tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


You can get its value as a Numpy array by calling `.numpy()`:

In [4]:
import numpy as np
y = np.array([[1, 2, 2], [8, 2, 5]])
print(y)
# We can also convert a tensor into a numpy array by using .numpy()
c.numpy()

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

In [5]:
print('Tensor Data Type', c.dtype)
print('Tensor Shape', c.shape)
# You can notice the similarity with numpy 
# You can also call the different default tensors as you would do for numpy

Tensor Data Type <dtype: 'float32'>
Tensor Shape (2, 3)


In [6]:
random_variable = tf.ones(shape=(3,3))
#random variable
tf_variable = tf.Variable(random_variable)
print(tf_variable)

#you can also update the values of your variable.
tf_variable.assign(tf.zeros(shape = (3,3)))
print(tf_variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


In [7]:
# computing derivative for the function 3x^2 at x = 3

x = tf.constant(3.0) #gradient at
with tf.GradientTape() as g:
  g.watch(x) #record the operations
  y = 3*x * x
dy_dx = g.gradient(y, x) 
print(dy_dx)


# you can also use nested GradientTape() for the second derivative
#computing second derivative for the function 4x^2 at x = 4.0

x = tf.constant(4.0)
with tf.GradientTape() as gt:
  gt.watch(x)
  with tf.GradientTape() as g:
    g.watch(x)  
    y = 4*x*x
  dy_dx = g.gradient(y, x)
d2y_dx2 = gt.gradient(dy_dx,x)
print(d2y_dx2)





tf.Tensor(18.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


#### 1. Create a constant tensor array 'x' like [2,3,4] and find element wise e^x.  Refer to the website [here](https://www.tensorflow.org/api_docs/python/tf/math/exp).

In [10]:
x = tf.constant([2.0,3.0,4.0])
x = tf.math.exp(x)
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 7.389056, 20.085537, 54.59815 ], dtype=float32)>

#### 2. Declare a variable with a 3*2 shaped floating elements array with elements picked from a random normal distributions.   

In [11]:
x = tf.Variable(tf.random.normal(shape=(3,2)))
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.08080089, -0.7743149 ],
       [ 0.27444255,  0.02577921],
       [ 1.4908392 ,  2.083642  ]], dtype=float32)>

#### 3. Subtract 1 from every element of the above matrix.

In [12]:
x.assign_sub(tf.ones(shape=(3,2)))

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[-1.0808009 , -1.7743149 ],
       [-0.72555745, -0.9742208 ],
       [ 0.49083924,  1.083642  ]], dtype=float32)>

#### 4. Calculate the third derivative of the function 4x^3 + x^2 + 1 at x = 1

In [21]:
x = tf.constant(1.0)
with tf.GradientTape() as g:
  g.watch(x)
  with tf.GradientTape() as g1:
    g1.watch(x)
    with tf.GradientTape() as g2:
      g2.watch(x)
      y = 4*x**3 + x**2 + 1
      dy_dx = g.gradient(y,x)
      dy_dx2 = g1.gradient(dy_dx,x)
      dy_dx3 = g2.gradient(dy_dx2,x)
dy_dx3



<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

#### 5. Calculate dot product of matrices [[1,2,3],[4,5,6],[7,8,9]] and [[1],[2],[3]] using tensorflow functions. Also, find the element wise multiplication of the two.

In [22]:
A = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
B = tf.constant([[1],[2],[3]])
tf.matmul(A,B)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[14],
       [32],
       [50]], dtype=int32)>

In [23]:
tf.multiply(A,B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]], dtype=int32)>